version: "3.9"
services:
  # Rails
  app:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      DB_HOST: db
    volumes:
      - .:/myapp
      - public:/myapp/public
      - tmp:/myapp/tmp
    env_file:
      - .env
    stdin_open: true
    tty: true

  # Nginx
  web:
    build:
      context: containers/nginx
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/myapp/public
      - tmp:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  bundle:
  tmp:
  public:
