version: "3.9"
services:
  # DB
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  # Rails
  app:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      DB_HOST: db
    volumes:
      - .:/myapp
      - public:/myapp/public
      - tmp:/myapp/tmp
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  # Nginx
  web:
    build:
      context: containers/nginx
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/myapp/public
      - tmp:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  bundle:
  db:
  tmp:
  public:
