version: "3.9"
services:
  # DB container
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # - ./containers/mysql:/etc/mysql/conf.d/
      - db:/var/lib/mysql

  # Rails container
  app:
    # build: .
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec puma -C config/puma.rb
    environment:
      DB_HOST: db
    volumes:
      - .:/myapp
      - public:/myapp/public
      - tmp:/myapp/tmp
    # NginxとPumaがソケットでバインドするため、3000ポートを開ける必要がない。
    # ports:
    #   - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  # Nginx container
  web:
    build:
      context: containers/nginx
      # context: .
      # dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/myapp/public
      - tmp:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  bundle:
  db:
  tmp:
  public:
