version: "3.9"
services:
  # Rails
  app:
    image: ${ECR_RAILS_REPO}
    command: bash -c "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/myapp
      - public:/myapp/public
      - tmp:/myapp/tmp
    env_file:
      - .env
    logging:
      driver: awslogs
      options: 
          awslogs-group: test
          awslogs-region: ap-northeast-1
          awslogs-stream-prefix: rails 

  # Nginx
  web:
    image: ${ECR_NGINX_REPO}
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/myapp/public
      - tmp:/myapp/tmp
    ports:
      - 80:80
    logging:
      driver: awslogs
      options: 
          awslogs-group: test
          awslogs-region: ap-northeast-1
          awslogs-stream-prefix: nginx 

volumes:
  bundle:
  tmp:
  public:
