version: "3.9"
services:
  # DB container
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '4306:3306'

  # Rails container
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  # Nginx container

volumes:
  bundle:
  mysql:
