version: "3.9"
services:
  # DB container
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  # Rails container
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    environment:
      DB_HOST: db
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    user: root

  # Nginx container
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  bundle:
  db:
